AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - ".git/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "spec/**/*"
    - "node_modules/**/*"
    - "bin/**"
    - "Gemfile"
    - "Rakefile"
    - "app/channels/**/*"
    - "vendor/**/*"
Layout/IndentationWidth:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# 日本語のコメントアウトを許可する
Style/AsciiComments:
  Enabled: false
# クラスを継承する前にコメントを書く必要はない
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
StringLiterals:
  EnforcedStyle: single_quotes
Metrics/MethodLength:
  Enabled: false
