default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['RECOFIT_DB_HOST'] %>
  username: <%= ENV['RECOFIT_DB_USER'] %>
  password: <%= ENV['RECOFIT_DB_PASSWORD'] %>

development:
  <<: *default
  database: recofit_development
  # host: <%= ENV['RECOFIT_DB_HOST'] %>

test:
  <<: *default
  database: recofit_test

production:
  <<: *default
  database: recofit_production
  # host: <%= ENV['RECOFIT_DB_HOST'] %>
  # username: <%= ENV['RECOFIT_DB_USER'] %>
  # password: <%= ENV['RECOFIT_DB_PASSWORD'] %>
